In [21]:
import numpy as np

In [22]:
arr = np.arange(5)

In [23]:
arr

array([0, 1, 2, 3, 4])

In [24]:
np.save('myarray.npy',arr)

In [25]:
arr = np.arange(10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [28]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [29]:
arr2 = arr

In [30]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [32]:
archive_array = np.load('ziparray.npz')

In [33]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [35]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr = np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [39]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [40]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [42]:
arr.mean()

3.5