In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.04782669,  1.51777562,  2.45020173,  0.71975025,  0.32312565,
       -0.31595801,  1.13272858, -0.32012713,  0.42804868, -0.99056159])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-1.68759246, -1.38161395, -0.29772813, -0.67864253, -0.1905696 ,
       -0.43053275, -0.91416253,  0.82461605,  2.75902051, -0.1543428 ])

In [10]:
# Binary Functions
np.add(A,B)

array([-1.63976578,  0.13616166,  2.1524736 ,  0.04110772,  0.13255605,
       -0.74649077,  0.21856605,  0.50448892,  3.18706919, -1.14490439])

In [11]:
np.maximum(A,B)

array([ 0.04782669,  1.51777562,  2.45020173,  0.71975025,  0.32312565,
       -0.31595801,  1.13272858,  0.82461605,  2.75902051, -0.1543428 ])